language: rust
cache:
  directories:
  - cargo_web

rust:
  - stable
  - beta
  - nightly
  - 1.22.0
os:
 - linux
 - windows

addons:
  chrome: stable

matrix:
  exclude:
  - rust: 1.22.0
    os: windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    choco install python3 --version 3.8 || (cat /c/ProgramData/chocolatey/logs/chocolatey.log && false) &&
    export PATH="/c/Python38:/c/Python38/Scripts:$PATH" &&
    shopt -s expand_aliases &&
    alias python3="py -3";
    fi

script:
  - python3 --version
  - python3 ./contrib/tests.py
