[package]

name = "secp256k1-sgx"
version = "0.11.1"
authors = [ "Fan Zhang <fanz@cs.cornell.edu>" ]
license = "CC0-1.0"
homepage = "https://github.com/bl4ck5un/rust-secp256k1-sgx/"
repository = "https://github.com/bl4ck5un/rust-secp256k1-sgx/"
description = "SGX Port of the crate `secp256k1`, Rust bindings for Pieter Wuille's `libsecp256k1` library. Implements ECDSA for the SECG elliptic curve group secp256k1 and related utilities."
keywords = [ "crypto", "ECDSA", "secp256k1", "libsecp256k1", "bitcoin" ]
readme = "README.md"
build = "build.rs"

# Should make docs.rs show all functions, even those behind non-default features
[package.metadata.docs.rs]
rustdoc-args = [
    "--features \"rand serde\""
]

[lib]
name = "secp256k1"
path = "src/lib.rs"

[features]
default = []
rand = ["sgx_rand"]

[dependencies]
libc = {version = "0.2", default-features = false}

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_rand = { git = "https://github.com/baidu/rust-sgx-sdk", optional = true }